---
abstract: 'Tapper - Remote network API for result evaluation'
author:
  - 'AMD OSRC Tapper Team <tapper@amd64.org>'
build_requires:
  Cwd: 0
  ExtUtils::MakeMaker: 6.42
  Tapper::Test: 3.000002
  Test::Deep: 0
  Test::Fixture::DBIC::Schema: 0
  Test::More: 0
  Test::Perl::Critic: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: freebsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tapper-Reports-API
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Data::Structure::Util: 0
  Module::Build: 0
  Moose: 0.72
  MooseX::Daemonize: 0.08
  Net::Server: 0
  Tapper::Config: 3.000002
  Tapper::Reports::DPath: 3.000002
  Tapper::Schema: 3.000002
  perl: 5.010
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Tapper-Reports-API
  repository: git://github.com/amd/Tapper-Reports-API.git
version: 3.000004
